spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/orderDB
    username: postgres
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  servlet:
    context-path: /orders
  port: 9010

